name: GOV.UK prototype kit test
description: Test the package with the GOV.UK prototype kit

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: .nvmrc
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Build package
      run: >
        npm run build:package &&
        cd package &&
        npm pack --pack-destination .
      shell: bash
    - name: Create prototype
      run: >
        mkdir prototype &&
        cd prototype &&
        npx govuk-prototype-kit create
      shell: bash
    - name: Create usage data config
      run: echo "{\"collectUsageData\":false}" > prototype/usage-data-config.json
      shell: bash
    - name: Install package
      run: >
        cd prototype &&
        npm install ../package/nationalarchives-frontend-$(node -p "require('../package.json').version").tgz
      shell: bash
    - name: Add imports to template
      run: >
        echo -e "{% from \"nationalarchives/components/accordion/macro.njk\" import tnaAccordion %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/back-link/macro.njk\" import tnaBackLink %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/breadcrumbs/macro.njk\" import tnaBreadcrumbs %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/button/macro.njk\" import tnaButton %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/card/macro.njk\" import tnaCard %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/checkboxes/macro.njk\" import tnaCheckboxes %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/code-block/macro.njk\" import tnaCodeBlock %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/compound-filters/macro.njk\" import tnaCompoundFilters %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/cookie-banner/macro.njk\" import tnaCookieBanner %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/date-input/macro.njk\" import tnaDateInput %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/date-search/macro.njk\" import tnaDateSearch %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/details/macro.njk\" import tnaDetails %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/error-summary/macro.njk\" import tnaErrorSummary %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/fieldset/macro.njk\" import tnaFieldset %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/file-input/macro.njk\" import tnaFileInput %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/files-list/macro.njk\" import tnaFilesList %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/footer/macro.njk\" import tnaFooter %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/gallery/macro.njk\" import tnaGallery %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/global-header/macro.njk\" import tnaGlobalHeader %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/header/macro.njk\" import tnaHeader %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/hero/macro.njk\" import tnaHero %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/index-grid/macro.njk\" import tnaIndexGrid %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/pagination/macro.njk\" import tnaPagination %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/panel/macro.njk\" import tnaPanel %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/phase-banner/macro.njk\" import tnaPhaseBanner %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/picture/macro.njk\" import tnaPicture %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/quick-filters/macro.njk\" import tnaQuickFilters %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/radios/macro.njk\" import tnaRadios %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/search-field/macro.njk\" import tnaSearchField %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/secondary-navigation/macro.njk\" import tnaSecondaryNavigation %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/select/macro.njk\" import tnaSelect %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/sidebar/macro.njk\" import tnaSidebar %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/skip-link/macro.njk\" import tnaSkipLink %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/tabs/macro.njk\" import tnaTabs %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/text-input/macro.njk\" import tnaTextInput %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/textarea/macro.njk\" import tnaTextarea %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/components/warning/macro.njk\" import tnaWarning %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html &&
        echo -e "{% from \"nationalarchives/utilities/grid/macro.njk\" import tnaGrid %}\n$(cat prototype/app/views/index.html)" > prototype/app/views/index.html
      shell: bash
    - name: Add components to template
      run: >
        echo "\n{% block bodyEnd %}" >> prototype/app/views/index.html &&
        echo "{{ tnaAccordion({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaBackLink({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaBreadcrumbs({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaButton({text:\"I am a button\",href:\"#\"}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaCard({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaCheckboxes({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaCodeBlock({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaCompoundFilters({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaCookieBanner({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaDateInput({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaDateSearch({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaDetails({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaErrorSummary({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaFieldset({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaFileInput({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaFilesList({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaFooter({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaGallery({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaGlobalHeader({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaGrid({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaHeader({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaHero({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaIndexGrid({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaPagination({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaPanel({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaPhaseBanner({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaPicture({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaQuickFilters({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaRadios({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaSearchField({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaSecondaryNavigation({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaSelect({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaSidebar({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaSkipLink({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaTabs({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaTextInput({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaTextarea({}) }}" >> prototype/app/views/index.html &&
        echo "{{ tnaWarning({}) }}" >> prototype/app/views/index.html &&
        echo "{% endblock %}" >> prototype/app/views/index.html
      shell: bash
    - name: Copy page templates
      run: >
        cp package/nationalarchives/templates/prototype-kit/plain.njk prototype/app/views/template-plain.html &&
        cp package/nationalarchives/templates/prototype-kit/list.njk prototype/app/views/template-list.html &&
        cp package/nationalarchives/templates/prototype-kit/index-grid.njk prototype/app/views/template-index-grid.html
      shell: bash
    - name: Run prototype
      run: >
        cd prototype &&
        npm run dev &
      shell: bash
    - uses: nev7n/wait_for_response@7fef3c1a6e8939d0b09062f14fec50d3c5d15fa1 # v1.0.1
      with:
        url: "http://localhost:3000"
        responseCode: 200
        timeout: 30000
        interval: 500
    - name: Test prototype components
      run: >
        curl --silent http://localhost:3000 | grep '<div class="tna-accordion' || (echo "Accordion component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<a href="" class="tna-back-link' || (echo "Back link component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<nav class="tna-breadcrumbs' || (echo "Breadcrumbs component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<a href="#" class="tna-button' || (echo "Button component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<article class="tna-card' || (echo "Card component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-checkboxes' || (echo "Checkboxes component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-code-block' || (echo "Code block component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-compound-filters' || (echo "Compound filters component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-cookie-banner' || (echo "Cookie banner component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-date-input' || (echo "Date input component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-date-search' || (echo "Date search component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-details' || (echo "Details component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-error-summary' || (echo "Error summary component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-fieldset' || (echo "Fieldset component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-file-input' || (echo "File input component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-files-list' || (echo "Files list component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<footer class="tna-footer' || (echo "Footer component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-gallery' || (echo "Gallery component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<header class="tna-global-header' || (echo "Global header component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<header class="tna-header' || (echo "Header component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-hero' || (echo "Hero component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-index-grid' || (echo "Index grid component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<nav class="tna-pagination' || (echo "Pagination component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-panel' || (echo "Panel component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-phase-banner' || (echo "Phase banner component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-picture' || (echo "Picture component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-quick-filters' || (echo "Quick filters component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-radios' || (echo "Radios component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-search-field' || (echo "Search field component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<nav class="tna-secondary-navigation' || (echo "Secondary navigation component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-select' || (echo "Select component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<nav class="tna-sidebar' || (echo "Sidebar component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<a href="#" class="tna-skip-link' || (echo "Skip link component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-tabs' || (echo "Tabs component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-text-input' || (echo "Text input component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-textarea' || (echo "Textarea component not found" && exit 1)
        curl --silent http://localhost:3000 | grep '<div class="tna-warning' || (echo "Warning component not found" && exit 1)
      shell: bash
    - name: Test templates
      run: >
        curl --silent --fail http://localhost:3000/template-plain > /dev/null &&
        curl --silent --fail http://localhost:3000/template-list > /dev/null &&
        curl --silent --fail http://localhost:3000/template-index-grid > /dev/null
      shell: bash
