name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      testAllStories:
        type: boolean
        description: Test all stories on Chromatic
        required: false
        default: false

permissions:
  contents: read

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npm run build:storybook:tests
      - uses: chromaui/action@latest
        if: ${{ inputs.testAllStories != 'true' }}
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook
          exitZeroOnChanges: true
          onlyChanged: true
          externals: |
            - (.storybook|src)/**
      - uses: chromaui/action@latest
        if: ${{ inputs.testAllStories == 'true' }}
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: storybook
          exitZeroOnChanges: true
          forceRebuild: true
          onlyChanged: false
